#-Dspring.profiles.active=production -Dspring.config.location=file:/application.yml

server:
    port: 8081
tcpNetServer:
    port: 4561
---

spring:
    profiles: production
server:
    port: 0
tcpNetServer:
    port: 4561
logging:
    file: log/flow.log