#-Dspring.profiles.active=production -Dspring.config.location=file:/application.yml

server:
    port: 8082
tcpNetServer:
    port: 4561
instance:
    name: Flow
---

spring:
    profiles: production
server:
    port: 0
tcpNetServer:
    port: 4561
instance:
    name: Flow
logging:
    file: log/flow.log