#WLOG_OPTS="-Dspring.profiles.active=production -Dspring.config.location=file:/application.yml" wlog.bat

server:
    port: 8081
tcpNetServer:
    port: 4561
debug: true
---

spring:
    profiles: production
server:
    port: 0
tcpNetServer:
    port: 4561
logging:
    file: log/flow.log
debug: false